spring.application.name=architecture-starter

# H2 en memoire -- uniquement pour la demo du template
spring.datasource.url=jdbc:h2:mem:archstarter;DB_CLOSE_DELAY=-1
spring.jpa.hibernate.ddl-auto=update
